$(document).ready(function(){
	$('.img_anbum').click(function(){
		$('#img_show').attr('src',$(this).attr('src'));
		$('.title').text($(this).next().html())
		$('.show').addClass('ative');
	})
	$('.icon').click(function(){
		$('.show').removeClass('ative');
	})
	$('#opacity').click(function(){
		$('.show').removeClass('ative');
	})
})